try {
  foo
} catch(myexception) {
  foo
}

try {
  foo
} finally {
  foo
}

try {
  foo
} catch(myexception) {
  foo
} finally {
  foo
}
